---
- name: Start Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ playbook_dir }}/../docker"

- name: Wait for Jellyfin
  uri:
    url: http://localhost:8096
    status_code: 200
  register: jellyfin
  retries: 20
  delay: 3
  until: jellyfin.status == 200

- name: Wait for Grafana
  uri:
    url: http://localhost:3000/login
    status_code: 200
  register: grafana
  retries: 20
  delay: 3
  until: grafana.status == 200

- name: Wait for Prometheus
  uri:
    url: http://localhost:9090
    status_code: 200
  register: prometheus
  retries: 20
  delay: 3
  until: prometheus.status == 200